# Generated by Django 6.0.4 on 2026-06-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nom_departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Red',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.PROTECT, to='usuario.departamento')),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Luminaria',
            fields=[
                ('id_luminaria', models.AutoField(primary_key=True, serialize=False)),
                ('potencia', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('red', models.ForeignKey(db_column='id_red', on_delete=django.db.models.deletion.PROTECT, to='usuario.red')),
            ],
            options={
                'db_table': 'Luminaria',
            },
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_inicio', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('periodo_fin', models.DateField()),
                ('luminaria', models.ForeignKey(db_column='id_luminaria', on_delete=django.db.models.deletion.PROTECT, to='usuario.luminaria')),
                ('tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RegistroConsumo',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('tipo_nivel', models.CharField(max_length=100, verbose_name='Tipo de Nivel')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('total_kwh', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total kWh')),
                ('total_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Costo')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador Responsable')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_zona', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.PROTECT, to='usuario.municipio')),
            ],
            options={
                'db_table': 'Zona',
            },
        ),
        migrations.AddField(
            model_name='red',
            name='zona',
            field=models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.PROTECT, to='usuario.zona'),
        ),
    ]
